sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rogergam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rogergam/docker-react npm run test